#include "RegistrySettingsData.h"

namespace optimizations {
namespace registry {

const std::vector<RegistrySettingDefinition>& GetRegistrySettingDefinitions() {
  static const std::vector<RegistrySettingDefinition> kRegistrySettings = {
    {
      std::string("win.maintenance.disable"),
      std::string("Windows Maintenance"),
      std::string("Controls Windows maintenance resource hogging tasks"),
      std::string("HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Schedule\\Maintenance"),
      std::string("MaintenanceDisabled"),
      OptimizationValue{0},
      OptimizationValue{1},
      std::string("System"),
      std::string("Maintenance"),
      false,
      true,
      false,
      1,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{0}, std::string("Enabled (default)")},
        {OptimizationValue{1}, std::string("Disabled (reduces resource usage)")},
      }
    },
    {
      std::string("win.desktop.menudelay"),
      std::string("Menu Show Delay"),
      std::string("Controls the delay before displaying menus and speeds up opening Start Menu"),
      std::string("HKEY_CURRENT_USER\\Control Panel\\Desktop"),
      std::string("MenuShowDelay"),
      OptimizationValue{std::string("400")},
      OptimizationValue{std::string("0")},
      std::string("System"),
      std::string("Desktop"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{std::string("400")}, std::string("Default delay")},
        {OptimizationValue{std::string("0")}, std::string("No delay (faster menu response)")},
      }
    },
    {
      std::string("win.system.responsiveness"),
      std::string("System Responsiveness"),
      std::string("Controls system responsiveness allocation value (lower means more resources for foreground tasks)"),
      std::string("HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile"),
      std::string("SystemResponsiveness"),
      OptimizationValue{20},
      OptimizationValue{0},
      std::string("System"),
      std::string("Performance"),
      true,
      true,
      false,
      2,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{20}, std::string("Default (balanced)")},
        {OptimizationValue{0}, std::string("Maximum responsiveness")},
      }
    },
    {
      std::string("win.priority.separation"),
      std::string("Windows Priority Scheduling"),
      std::string("Controls how Windows prioritizes foreground/background applications"),
      std::string("HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\PriorityControl"),
      std::string("Win32PrioritySeparation"),
      OptimizationValue{2},
      OptimizationValue{33},
      std::string("System"),
      std::string("CPU"),
      true,
      true,
      false,
      2,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{2}, std::string("Default")},
        {OptimizationValue{33}, std::string("Balanced (21 in hex)")},
        {OptimizationValue{40}, std::string("Experimental")},
      }
    },
    {
      std::string("win.power.fastboot"),
      std::string("Fast Startup"),
      std::string("Controls Fast Startup (Hybrid Boot) feature"),
      std::string("HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Session Manager\\Power"),
      std::string("HiberBootEnabled"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("System"),
      std::string("Power"),
      false,
      true,
      false,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Enabled (default)")},
        {OptimizationValue{0}, std::string("Disabled")},
      }
    },
    {
      std::string("win.sysmain.service"),
      std::string("SysMain Service (Superfetch)"),
      std::string("Controls SysMain service (formerly Superfetch) that prefetches data into memory"),
      std::string("HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Services\\SysMain"),
      std::string("Start"),
      OptimizationValue{2},
      OptimizationValue{4},
      std::string("System"),
      std::string("Services"),
      false,
      true,
      false,
      2,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{2}, std::string("Automatic (default)")},
        {OptimizationValue{4}, std::string("Disabled (prevents background memory prefetching, reduces disk activity and stutters with SSDs)")},
      }
    },
    {
      std::string("win.privacy.advertising.id"),
      std::string("Advertising ID"),
      std::string("Controls unique advertising ID for personalized ads"),
      std::string("HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\AdvertisingInfo"),
      std::string("Enabled"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("Privacy"),
      std::string("Advertising"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Enabled (default)")},
        {OptimizationValue{0}, std::string("Disabled (turns off unique advertising ID)")},
      }
    },
    {
      std::string("win.privacy.tailored.data"),
      std::string("Tailored Experiences with Diagnostic Data"),
      std::string("Controls tailored experiences based on diagnostic data collection"),
      std::string("HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Privacy"),
      std::string("TailoredExperiencesWithDiagnosticDataEnabled"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("Privacy"),
      std::string("Diagnostics"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Enabled (default)")},
        {OptimizationValue{0}, std::string("Disabled (reduces background processing of usage patterns)")},
      }
    },
    {
      std::string("win.mouse.acceleration"),
      std::string("Mouse Acceleration"),
      std::string("Controls mouse acceleration (enhances pointing precision)"),
      std::string("HKEY_CURRENT_USER\\Control Panel\\Mouse"),
      std::string("MouseSpeed"),
      OptimizationValue{std::string("1")},
      OptimizationValue{std::string("0")},
      std::string("Input"),
      std::string("Mouse"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{std::string("1")}, std::string("Enabled (default)")},
        {OptimizationValue{std::string("0")}, std::string("Disabled (raw input, better for gaming)")},
      }
    },
    {
      std::string("win.mouse.threshold1"),
      std::string("Mouse Acceleration Threshold 1"),
      std::string("Controls first threshold for mouse acceleration"),
      std::string("HKEY_CURRENT_USER\\Control Panel\\Mouse"),
      std::string("MouseThreshold1"),
      OptimizationValue{std::string("6")},
      OptimizationValue{std::string("0")},
      std::string("Input"),
      std::string("Mouse"),
      true,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{std::string("6")}, std::string("Default threshold")},
        {OptimizationValue{std::string("0")}, std::string("No threshold (raw input, better for gaming)")},
      }
    },
    {
      std::string("win.mouse.threshold2"),
      std::string("Mouse Acceleration Threshold 2"),
      std::string("Controls second threshold for mouse acceleration"),
      std::string("HKEY_CURRENT_USER\\Control Panel\\Mouse"),
      std::string("MouseThreshold2"),
      OptimizationValue{std::string("10")},
      OptimizationValue{std::string("0")},
      std::string("Input"),
      std::string("Mouse"),
      true,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{std::string("10")}, std::string("Default threshold")},
        {OptimizationValue{std::string("0")}, std::string("No threshold (raw input, better for gaming)")},
      }
    },
    {
      std::string("win.mouse.acceleration.wrapper"),
      std::string("Mouse Acceleration"),
      std::string("Controls mouse acceleration and pointer precision settings for gaming (combines MouseSpeed, MouseThreshold1, and MouseThreshold2)"),
      std::string("HKEY_CURRENT_USER\\Control Panel\\Mouse"),
      std::string("MouseSpeed"),
      OptimizationValue{false},
      OptimizationValue{false},
      std::string("Gaming"),
      std::string("Input"),
      false,
      true,
      true,
      0,
      false,
      false,
      true,
      {
        {std::string(""), std::string("MouseSpeed"), OptimizationValue{std::string("1")}, OptimizationValue{std::string("0")}},
        {std::string(""), std::string("MouseThreshold1"), OptimizationValue{std::string("6")}, OptimizationValue{std::string("0")}},
        {std::string(""), std::string("MouseThreshold2"), OptimizationValue{std::string("10")}, OptimizationValue{std::string("0")}},
      },
      {
        {OptimizationValue{false}, std::string("Disabled (Recommended for gaming)")},
        {OptimizationValue{true}, std::string("Enabled (Default Windows behavior)")},
      }
    },
    {
      std::string("win.accessibility.stickykeys"),
      std::string("Sticky Keys"),
      std::string("Controls Sticky Keys accessibility feature"),
      std::string("HKEY_CURRENT_USER\\Control Panel\\Accessibility\\StickyKeys"),
      std::string("Flags"),
      OptimizationValue{510},
      OptimizationValue{506},
      std::string("Accessibility"),
      std::string("Input"),
      false,
      true,
      true,
      1,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{510}, std::string("Default (enabled)")},
        {OptimizationValue{506}, std::string("Disabled")},
      }
    },
    {
      std::string("win.gamebar.nexus"),
      std::string("Game Bar Nexus"),
      std::string("Controls Game Bar Nexus feature"),
      std::string("HKEY_CURRENT_USER\\Software\\Microsoft\\GameBar"),
      std::string("UseNexusForGameBarEnabled"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("Gaming"),
      std::string("Game Bar"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Enabled (default)")},
        {OptimizationValue{0}, std::string("Disabled")},
      }
    },
    {
      std::string("win.gamebar.gamemode"),
      std::string("Auto Game Mode"),
      std::string("Controls automatic Game Mode activation"),
      std::string("HKEY_CURRENT_USER\\Software\\Microsoft\\GameBar"),
      std::string("AutoGameModeEnabled"),
      OptimizationValue{0},
      OptimizationValue{1},
      std::string("Gaming"),
      std::string("Game Mode"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{0}, std::string("Disabled (default)")},
        {OptimizationValue{1}, std::string("Enabled (automatically enables Game Mode for games)")},
      }
    },
    {
      std::string("win.gamedvr.enabled"),
      std::string("Game DVR"),
      std::string("Controls Game DVR for capturing gameplay"),
      std::string("HKEY_CURRENT_USER\\System\\GameConfigStore"),
      std::string("GameDVR_Enabled"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("Gaming"),
      std::string("Game DVR"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Enabled (default)")},
        {OptimizationValue{0}, std::string("Disabled (better performance)")},
      }
    },
    {
      std::string("win.telemetry.allowtelemetry"),
      std::string("Windows Telemetry"),
      std::string("Controls Windows diagnostic data collection level"),
      std::string("HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Policies\\DataCollection"),
      std::string("AllowTelemetry"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("Privacy"),
      std::string("Telemetry"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Basic (default)")},
        {OptimizationValue{0}, std::string("Security (minimal data collection)")},
      }
    },
    {
      std::string("win.telemetry.cpss"),
      std::string("CPSS Store Telemetry"),
      std::string("Controls telemetry for Connected Packages and Store Services"),
      std::string("HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\CPSS\\Store"),
      std::string("AllowTelemetry"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("Privacy"),
      std::string("Telemetry"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Enabled (default)")},
        {OptimizationValue{0}, std::string("send only required")},
      }
    },
    {
      std::string("win.device.metadata"),
      std::string("Device Metadata Download"),
      std::string("Controls automatic downloading of device metadata from the internet"),
      std::string("HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Device Metadata"),
      std::string("PreventDeviceMetadataFromNetwork"),
      OptimizationValue{0},
      OptimizationValue{1},
      std::string("Privacy"),
      std::string("Device Data"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{0}, std::string("Enabled (default)")},
        {OptimizationValue{1}, std::string("Disabled (prevents automatic downloads)")},
      }
    },
    {
      std::string("win.remote.assistance"),
      std::string("Remote Assistance"),
      std::string("Controls whether others can provide remote assistance to this computer"),
      std::string("HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\Remote Assistance"),
      std::string("fAllowToGetHelp"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("System"),
      std::string("Remote Access"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Enabled (default)")},
        {OptimizationValue{0}, std::string("Disabled")},
      }
    },
    {
      std::string("win.graphics.hwscheduling"),
      std::string("GPU Hardware Scheduling"),
      std::string("Controls hardware-accelerated GPU scheduling"),
      std::string("HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\GraphicsDrivers"),
      std::string("HwSchMode"),
      OptimizationValue{1},
      OptimizationValue{2},
      std::string("Gaming"),
      std::string("Graphics"),
      true,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Default")},
        {OptimizationValue{2}, std::string("Enabled (improved GPU performance)")},
      }
    },
    {
      std::string("win.transparency"),
      std::string("Transparency Effects"),
      std::string("Controls transparency effects in Windows UI elements"),
      std::string("HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize"),
      std::string("EnableTransparency"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("Visual Effects"),
      std::string("Windows UI"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Enabled (default)")},
        {OptimizationValue{0}, std::string("Disabled (better performance)")},
      }
    },
    {
      std::string("win.update.deliveryoptimization"),
      std::string("Delivery Optimization"),
      std::string("Allow downloads from other devices on the local network and internet"),
      std::string("HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\DeliveryOptimization\\DeliveryOptimization\\Config"),
      std::string("DODownloadMode"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("System"),
      std::string("Updates"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Enabled (default)")},
        {OptimizationValue{0}, std::string("Disabled (download only from Microsoft)")},
      }
    },
    {
      std::string("win.update.microsoftproducts"),
      std::string("Updates for Other Microsoft Products"),
      std::string("Receive updates for other Microsoft products when updating Windows"),
      std::string("HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\WindowsUpdate\\UX\\Settings"),
      std::string("AllowMUUpdateService"),
      OptimizationValue{0},
      OptimizationValue{1},
      std::string("System"),
      std::string("Updates"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{0}, std::string("Disabled (default)")},
        {OptimizationValue{1}, std::string("Enabled (get updates for Office, etc.)")},
      }
    },
    {
      std::string("win.update.getuptodate"),
      std::string("Get Me Up to Date"),
      std::string("Controls whether Windows actively checks for and installs updates"),
      std::string("HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\WindowsUpdate\\Auto Update"),
      std::string("AUOptions"),
      OptimizationValue{4},
      OptimizationValue{3},
      std::string("System"),
      std::string("Updates"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{2}, std::string("Notify before download")},
        {OptimizationValue{3}, std::string("Download and notify before install")},
        {OptimizationValue{4}, std::string("Automatic download and install (default)")},
      }
    },
    {
      std::string("win.explorer.hidefileext"),
      std::string("Hide File Extensions"),
      std::string("Controls whether file extensions are hidden in File Explorer"),
      std::string("HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced"),
      std::string("HideFileExt"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("File Explorer"),
      std::string("View Options"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Hidden (default)")},
        {OptimizationValue{0}, std::string("Visible (recommended for better file identification)")},
      }
    },
    {
      std::string("win.explorer.cloudfiles.quickaccess"),
      std::string("Cloud Files in Quick Access"),
      std::string("Controls whether cloud files are shown in Quick Access"),
      std::string("HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer"),
      std::string("ShowCloudFilesInQuickAccess"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("File Explorer"),
      std::string("Quick Access"),
      false,
      true,
      true,
      1,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Enabled (default)")},
        {OptimizationValue{0}, std::string("Disabled (cleaner Quick Access)")},
      }
    },
    {
      std::string("win.search.devicehistory"),
      std::string("Device Search History"),
      std::string("Controls whether device search history is enabled"),
      std::string("HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\SearchSettings"),
      std::string("IsDeviceSearchHistoryEnabled"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("Privacy"),
      std::string("Search"),
      false,
      true,
      true,
      1,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Enabled (default)")},
        {OptimizationValue{0}, std::string("Disabled (enhanced privacy)")},
      }
    },
    {
      std::string("win.explorer.fullpath.titlebar"),
      std::string("Display Full Path in Title Bar"),
      std::string("Shows complete file path in File Explorer title bar"),
      std::string("HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\CabinetState"),
      std::string("FullPath"),
      OptimizationValue{0},
      OptimizationValue{1},
      std::string("File Explorer"),
      std::string("Display"),
      false,
      true,
      true,
      1,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{0}, std::string("Disabled (default)")},
        {OptimizationValue{1}, std::string("Enabled (shows full path for better navigation)")},
      }
    },
    {
      std::string("win.sharing.wizard"),
      std::string("Sharing Wizard"),
      std::string("Controls the sharing wizard for network file sharing"),
      std::string("HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced"),
      std::string("SharingWizardOn"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("File Explorer"),
      std::string("Network"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Enabled (default)")},
        {OptimizationValue{0}, std::string("Disabled (advanced sharing options)")},
      }
    },
    {
      std::string("win.explorer.network.namespace"),
      std::string("Network in Navigation Pane"),
      std::string("Controls whether Network appears in File Explorer navigation pane"),
      std::string("HKEY_CURRENT_USER\\Software\\Classes\\CLSID\\{F02C1A0D-BE21-4350-88B0-7367FC96EF3C}"),
      std::string("System.IsPinnedToNameSpaceTree"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("File Explorer"),
      std::string("Navigation"),
      false,
      true,
      true,
      1,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Visible (default)")},
        {OptimizationValue{0}, std::string("Hidden (cleaner navigation pane)")},
      }
    },
    {
      std::string("win.audio.ducking.preference"),
      std::string("Audio Ducking Preference"),
      std::string("Controls how Windows reduces volume of other sounds during communications"),
      std::string("HKEY_CURRENT_USER\\Software\\Microsoft\\Multimedia\\Audio"),
      std::string("UserDuckingPreference"),
      OptimizationValue{2},
      OptimizationValue{3},
      std::string("Audio"),
      std::string("Communications"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{0}, std::string("Mute all other sounds")},
        {OptimizationValue{1}, std::string("Reduce volume by 80%")},
        {OptimizationValue{2}, std::string("Reduce volume by 50% (default)")},
        {OptimizationValue{3}, std::string("Do nothing (no ducking)")},
      }
    },
    {
      std::string("win.notifications.account"),
      std::string("Account Notifications"),
      std::string("Controls account-related notifications from Windows"),
      std::string("HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\SystemSettings\\AccountNotifications"),
      std::string("EnableAccountNotifications"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("Privacy"),
      std::string("Notifications"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Enabled (default)")},
        {OptimizationValue{0}, std::string("Disabled (fewer distractions)")},
      }
    },
    {
      std::string("win.privacy.location.global"),
      std::string("Global Location Access"),
      std::string("Controls global location access for all applications"),
      std::string("HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore\\location"),
      std::string("Value"),
      OptimizationValue{std::string("Allow")},
      OptimizationValue{std::string("Deny")},
      std::string("Privacy"),
      std::string("Location"),
      false,
      true,
      true,
      1,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{std::string("Allow")}, std::string("Allow location access (default)")},
        {OptimizationValue{std::string("Deny")}, std::string("Deny location access (enhanced privacy)")},
      }
    },
    {
      std::string("win.privacy.location.override"),
      std::string("User Location Override Privacy"),
      std::string("Controls user location override privacy setting"),
      std::string("HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\CPSS\\Store\\UserLocationOverridePrivacySetting"),
      std::string("Value"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("Privacy"),
      std::string("Location"),
      false,
      true,
      true,
      1,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Enabled (default)")},
        {OptimizationValue{0}, std::string("Disabled (enhanced privacy)")},
      }
    },
    {
      std::string("win.privacy.voice.activation"),
      std::string("Voice Activation"),
      std::string("Controls voice activation for all applications"),
      std::string("HKEY_CURRENT_USER\\Software\\Microsoft\\Speech_OneCore\\Settings\\VoiceActivation\\UserPreferenceForAllApps"),
      std::string("AgentActivationEnabled"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("Privacy"),
      std::string("Voice"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Enabled (default)")},
        {OptimizationValue{0}, std::string("Disabled (enhanced privacy)")},
      }
    },
    {
      std::string("win.privacy.voice.activation.lastused"),
      std::string("Voice Activation Last Used"),
      std::string("Controls voice activation last used tracking"),
      std::string("HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Speech_OneCore\\Settings\\VoiceActivation\\UserPreferenceForAllApps"),
      std::string("AgentActivationLastUsed"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("Privacy"),
      std::string("Voice"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Enabled (default)")},
        {OptimizationValue{0}, std::string("Disabled (enhanced privacy)")},
      }
    },
    {
      std::string("win.privacy.notifications.listener"),
      std::string("User Notification Listener"),
      std::string("Controls access to user notifications by applications"),
      std::string("HKEY_LOCAL_MACHINE\\Software\\Microsoft\\Windows\\CurrentVersion\\CapabilityAccessManager\\ConsentStore\\userNotificationListener"),
      std::string("Value"),
      OptimizationValue{std::string("Allow")},
      OptimizationValue{std::string("Deny")},
      std::string("Privacy"),
      std::string("Notifications"),
      false,
      true,
      true,
      1,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{std::string("Allow")}, std::string("Allow notification access (default)")},
        {OptimizationValue{std::string("Deny")}, std::string("Deny notification access (enhanced privacy)")},
      }
    },
    {
      std::string("win.privacy.language.list"),
      std::string("Website Language List Access"),
      std::string("Controls whether websites can access your language list for localization"),
      std::string("HKEY_CURRENT_USER\\Control Panel\\International\\User Profile"),
      std::string("HttpAcceptLanguageOptOut"),
      OptimizationValue{0},
      OptimizationValue{1},
      std::string("Privacy"),
      std::string("Language"),
      false,
      true,
      true,
      1,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{0}, std::string("Allow language list access (default)")},
        {OptimizationValue{1}, std::string("Block language list access (enhanced privacy)")},
      }
    },
    {
      std::string("win.privacy.mfu.tracking.machine"),
      std::string("Most Frequently Used Tracking (Machine)"),
      std::string("Controls tracking of most frequently used apps for Start and Search (machine policy)"),
      std::string("HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\EdgeUI"),
      std::string("DisableMFUTracking"),
      OptimizationValue{0},
      OptimizationValue{1},
      std::string("Privacy"),
      std::string("Usage Tracking"),
      false,
      true,
      true,
      1,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{0}, std::string("Enable tracking (default)")},
        {OptimizationValue{1}, std::string("Disable tracking (enhanced privacy)")},
      }
    },
    {
      std::string("win.maps.autoupdate"),
      std::string("Maps Auto Update"),
      std::string("Controls automatic updating of offline maps"),
      std::string("HKEY_LOCAL_MACHINE\\SYSTEM\\Maps"),
      std::string("AutoUpdateEnabled"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("Privacy"),
      std::string("Maps"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Enabled (default)")},
        {OptimizationValue{0}, std::string("Disabled (saves bandwidth)")},
      }
    },
    {
      std::string("win.apps.automatic.archiving"),
      std::string("Automatic App Archiving"),
      std::string("Controls automatic archiving of unused applications"),
      std::string("HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\Appx"),
      std::string("AllowAutomaticAppArchiving"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("System"),
      std::string("Apps"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Enabled (default)")},
        {OptimizationValue{0}, std::string("Disabled (keeps apps fully available)")},
      }
    },
    {
      std::string("win.theme.dark.wrapper"),
      std::string("Dark Theme"),
      std::string("Controls dark theme for apps and system UI (combines AppsUseLightTheme for user and machine, and SystemUsesLightTheme)"),
      std::string("HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize"),
      std::string("AppsUseLightTheme"),
      OptimizationValue{false},
      OptimizationValue{true},
      std::string("Visual Effects"),
      std::string("Theme"),
      false,
      true,
      true,
      1,
      false,
      false,
      true,
      {
        {std::string("HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize"), std::string("AppsUseLightTheme"), OptimizationValue{0}, OptimizationValue{1}},
        {std::string("HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize"), std::string("SystemUsesLightTheme"), OptimizationValue{0}, OptimizationValue{1}},
        {std::string("HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Themes\\Personalize"), std::string("AppsUseLightTheme"), OptimizationValue{0}, OptimizationValue{1}},
      },
      {
        {OptimizationValue{true}, std::string("Dark theme (easier on eyes)")},
        {OptimizationValue{false}, std::string("Light theme (default)")},
      }
    },
    {
      std::string("win.gaming.tasks.priority"),
      std::string("Gaming Tasks Priority"),
      std::string("Controls the priority level for gaming tasks in Windows multimedia system profile"),
      std::string("HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games"),
      std::string("Priority"),
      OptimizationValue{2},
      OptimizationValue{6},
      std::string("Gaming"),
      std::string("Performance"),
      true,
      true,
      false,
      2,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{2}, std::string("Default priority")},
        {OptimizationValue{6}, std::string("High priority (better gaming performance)")},
      }
    },
    {
      std::string("win.gaming.tasks.gpu.priority"),
      std::string("Gaming Tasks GPU Priority"),
      std::string("Controls the GPU priority level for gaming tasks in Windows multimedia system profile"),
      std::string("HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games"),
      std::string("GPU Priority"),
      OptimizationValue{8},
      OptimizationValue{8},
      std::string("Gaming"),
      std::string("Performance"),
      true,
      true,
      false,
      2,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{8}, std::string("High GPU priority (default and recommended)")},
      }
    },
    {
      std::string("win.gaming.tasks.scheduling.category"),
      std::string("Gaming Tasks Scheduling Category"),
      std::string("Controls the scheduling category for gaming tasks in Windows multimedia system profile"),
      std::string("HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games"),
      std::string("Scheduling Category"),
      OptimizationValue{std::string("Medium")},
      OptimizationValue{std::string("High")},
      std::string("Gaming"),
      std::string("Performance"),
      true,
      true,
      false,
      2,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{std::string("Medium")}, std::string("Default scheduling category")},
        {OptimizationValue{std::string("High")}, std::string("High priority scheduling (better gaming performance)")},
      }
    },
    {
      std::string("win.gaming.tasks.sfio.priority"),
      std::string("Gaming Tasks SFIO Priority"),
      std::string("Controls the SFIO (Sequential File I/O) priority for gaming tasks in Windows multimedia system profile"),
      std::string("HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Multimedia\\SystemProfile\\Tasks\\Games"),
      std::string("SFIO Priority"),
      OptimizationValue{std::string("Normal")},
      OptimizationValue{std::string("High")},
      std::string("Gaming"),
      std::string("Performance"),
      true,
      true,
      false,
      2,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{std::string("Normal")}, std::string("Default SFIO priority")},
        {OptimizationValue{std::string("High")}, std::string("High SFIO priority (better gaming performance)")},
      }
    },
    {
      std::string("win.copilot.disable.wrapper"),
      std::string("Windows Copilot"),
      std::string("Controls Windows Copilot feature for both user and system-wide (combines user and machine policies)"),
      std::string("HKEY_CURRENT_USER\\Software\\Policies\\Microsoft\\Windows\\WindowsCopilot"),
      std::string("TurnOffWindowsCopilot"),
      OptimizationValue{false},
      OptimizationValue{true},
      std::string("System"),
      std::string("Copilot"),
      false,
      true,
      true,
      0,
      false,
      false,
      true,
      {
        {std::string("HKEY_CURRENT_USER\\Software\\Policies\\Microsoft\\Windows\\WindowsCopilot"), std::string("TurnOffWindowsCopilot"), OptimizationValue{1}, OptimizationValue{0}},
        {std::string("HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsCopilot"), std::string("TurnOffWindowsCopilot"), OptimizationValue{1}, OptimizationValue{0}},
      },
      {
        {OptimizationValue{true}, std::string("Disabled (removes Copilot integration)")},
        {OptimizationValue{false}, std::string("Enabled (default)")},
      }
    },
    {
      std::string("win.edge.performance.wrapper"),
      std::string("Microsoft Edge Optimization"),
      std::string("Optimizes Microsoft Edge for better system performance (combines startup boost, hardware acceleration, and background mode)"),
      std::string("HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Edge"),
      std::string("StartupBoostEnabled"),
      OptimizationValue{false},
      OptimizationValue{true},
      std::string("System"),
      std::string("Edge"),
      false,
      true,
      true,
      0,
      false,
      false,
      true,
      {
        {std::string("HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Edge"), std::string("StartupBoostEnabled"), OptimizationValue{0}, OptimizationValue{1}},
        {std::string("HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Edge"), std::string("HardwareAccelerationModeEnabled"), OptimizationValue{0}, OptimizationValue{1}},
        {std::string("HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Edge"), std::string("BackgroundModeEnabled"), OptimizationValue{0}, OptimizationValue{1}},
      },
      {
        {OptimizationValue{true}, std::string("Optimized (reduced resource usage)")},
        {OptimizationValue{false}, std::string("Default (full features enabled)")},
      }
    },
    {
      std::string("win.privacy.tracking.disable.wrapper"),
      std::string("Usage Tracking"),
      std::string("Controls tracking of most frequently used apps for Start and Search (combines user and machine policies)"),
      std::string("HKEY_CURRENT_USER\\Software\\Policies\\Microsoft\\Windows\\EdgeUI"),
      std::string("DisableMFUTracking"),
      OptimizationValue{false},
      OptimizationValue{true},
      std::string("Privacy"),
      std::string("Usage Tracking"),
      false,
      true,
      true,
      0,
      false,
      false,
      true,
      {
        {std::string("HKEY_CURRENT_USER\\Software\\Policies\\Microsoft\\Windows\\EdgeUI"), std::string("DisableMFUTracking"), OptimizationValue{1}, OptimizationValue{0}},
        {std::string("HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\EdgeUI"), std::string("DisableMFUTracking"), OptimizationValue{1}, OptimizationValue{0}},
      },
      {
        {OptimizationValue{true}, std::string("Disabled (enhanced privacy)")},
        {OptimizationValue{false}, std::string("Enabled (default)")},
      }
    },
    {
      std::string("win.taskbar.chat"),
      std::string("Taskbar Chat"),
      std::string("Controls the Chat (Meet Now) button on the taskbar"),
      std::string("HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced"),
      std::string("TaskbarMn"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("Visual Effects"),
      std::string("Taskbar"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Visible (default)")},
        {OptimizationValue{0}, std::string("Hidden (cleaner taskbar)")},
      }
    },
    {
      std::string("win.taskbar.taskview"),
      std::string("Taskbar Task View"),
      std::string("Controls the Task View button on the taskbar"),
      std::string("HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced"),
      std::string("ShowTaskViewButton"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("Visual Effects"),
      std::string("Taskbar"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Visible (default)")},
        {OptimizationValue{0}, std::string("Hidden (cleaner taskbar)")},
      }
    },
    {
      std::string("win.taskbar.copilot"),
      std::string("Taskbar Copilot"),
      std::string("Controls the Copilot button on the taskbar"),
      std::string("HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced"),
      std::string("ShowCopilotButton"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("Visual Effects"),
      std::string("Taskbar"),
      false,
      true,
      true,
      1,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Visible (default)")},
        {OptimizationValue{0}, std::string("Hidden (cleaner taskbar)")},
      }
    },
    {
      std::string("win.taskbar.meetnow"),
      std::string("Meet Now"),
      std::string("Controls the Meet Now feature in the taskbar"),
      std::string("HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Policies\\Explorer"),
      std::string("HideSCAMeetNow"),
      OptimizationValue{0},
      OptimizationValue{1},
      std::string("Visual Effects"),
      std::string("Taskbar"),
      false,
      true,
      true,
      1,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{0}, std::string("Visible (default)")},
        {OptimizationValue{1}, std::string("Hidden (cleaner taskbar)")},
      }
    },
    {
      std::string("win.taskbar.newsinterests"),
      std::string("News and Interests"),
      std::string("Controls the News and Interests widget on the taskbar"),
      std::string("HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\Windows Feeds"),
      std::string("EnableFeeds"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("Visual Effects"),
      std::string("Taskbar"),
      false,
      true,
      true,
      1,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Enabled (default)")},
        {OptimizationValue{0}, std::string("Disabled (cleaner taskbar)")},
      }
    },
    {
      std::string("win.start.recommendations"),
      std::string("Start Menu Recommendations"),
      std::string("Controls recommendations for tips, shortcuts, new apps and more in Start Menu"),
      std::string("HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced"),
      std::string("Start_IrisRecommendations"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("Visual Effects"),
      std::string("Start Menu"),
      false,
      true,
      true,
      1,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Enabled (default)")},
        {OptimizationValue{0}, std::string("Disabled (cleaner Start Menu)")},
      }
    },
    {
      std::string("win.display.dpi.logpixels"),
      std::string("DPI Log Pixels"),
      std::string("Controls the base DPI scaling value for the display"),
      std::string("HKEY_CURRENT_USER\\Control Panel\\Desktop"),
      std::string("LogPixels"),
      OptimizationValue{96},
      OptimizationValue{96},
      std::string("System"),
      std::string("Display"),
      true,
      true,
      true,
      2,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{96}, std::string("100% scaling (96 DPI)")},
        {OptimizationValue{120}, std::string("125% scaling (120 DPI)")},
        {OptimizationValue{144}, std::string("150% scaling (144 DPI)")},
      }
    },
    {
      std::string("win.display.dpi.win8scaling"),
      std::string("Windows 8 DPI Scaling"),
      std::string("Controls Windows 8 style DPI scaling behavior"),
      std::string("HKEY_CURRENT_USER\\Control Panel\\Desktop"),
      std::string("Win8DpiScaling"),
      OptimizationValue{0},
      OptimizationValue{1},
      std::string("System"),
      std::string("Display"),
      true,
      true,
      true,
      2,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{0}, std::string("Disabled (default)")},
        {OptimizationValue{1}, std::string("Enabled (alternative scaling method)")},
      }
    },
    {
      std::string("win.display.dwm.dpiscaling"),
      std::string("DWM DPI Scaling"),
      std::string("Controls DPI scaling behavior in Desktop Window Manager"),
      std::string("HKEY_CURRENT_USER\\SOFTWARE\\Microsoft\\Windows\\DWM"),
      std::string("UseDpiScaling"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("System"),
      std::string("Display"),
      true,
      true,
      true,
      2,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Enabled (default)")},
        {OptimizationValue{0}, std::string("Disabled (may improve app compatibility)")},
      }
    },
    {
      std::string("win.display.dpi.perprocess"),
      std::string("Per Process System DPI"),
      std::string("Controls per-process system DPI scaling for application compatibility"),
      std::string("HKEY_CURRENT_USER\\Control Panel\\Desktop"),
      std::string("EnablePerProcessSystemDPI"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("System"),
      std::string("Display"),
      true,
      true,
      true,
      2,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Enabled (default)")},
        {OptimizationValue{0}, std::string("Disabled (may improve scaling consistency)")},
      }
    },
    {
      std::string("win.store.autodownload"),
      std::string("Store Auto Download"),
      std::string("Controls automatic downloading of app updates from Microsoft Store"),
      std::string("HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\WindowsStore"),
      std::string("AutoDownload"),
      OptimizationValue{4},
      OptimizationValue{2},
      std::string("System"),
      std::string("Store"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{2}, std::string("Never auto-download (user control)")},
        {OptimizationValue{4}, std::string("Auto-download (default)")},
      }
    },
    {
      std::string("win.edge.background.mode"),
      std::string("Edge Background Mode"),
      std::string("Controls whether Microsoft Edge runs in background"),
      std::string("HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Edge"),
      std::string("BackgroundModeEnabled"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("System"),
      std::string("Edge"),
      false,
      true,
      true,
      1,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{1}, std::string("Enabled (default)")},
        {OptimizationValue{0}, std::string("Disabled (reduces background resource usage)")},
      }
    },
    {
      std::string("win.apps.background.execution"),
      std::string("Apps Background Execution"),
      std::string("Controls whether apps can run in the background"),
      std::string("HKEY_LOCAL_MACHINE\\SOFTWARE\\Policies\\Microsoft\\Windows\\AppPrivacy"),
      std::string("LetAppsRunInBackground"),
      OptimizationValue{0},
      OptimizationValue{2},
      std::string("Privacy"),
      std::string("Apps"),
      false,
      true,
      true,
      2,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{0}, std::string("User decides (default)")},
        {OptimizationValue{1}, std::string("Force allow")},
        {OptimizationValue{2}, std::string("Force deny (better performance)")},
      }
    },
    {
      std::string("win.search.web.startmenu"),
      std::string("Web Search in Start Menu"),
      std::string("Controls web search suggestions in Start Menu search"),
      std::string("HKEY_CURRENT_USER\\Software\\Policies\\Microsoft\\Windows\\Explorer"),
      std::string("DisableSearchBoxSuggestions"),
      OptimizationValue{0},
      OptimizationValue{1},
      std::string("Privacy"),
      std::string("Search"),
      false,
      true,
      true,
      0,
      false,
      false,
      false,
      {},
      {
        {OptimizationValue{0}, std::string("Enabled (default)")},
        {OptimizationValue{1}, std::string("Disabled (local search only)")},
      }
    },
    {
      std::string("win.wallpaper.master.control"),
      std::string("Desktop Background Mode"),
      std::string("Easy control for desktop background - automatically configures multiple wallpaper settings"),
      std::string("HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Wallpapers"),
      std::string("BackgroundType"),
      OptimizationValue{0},
      OptimizationValue{0},
      std::string("Appearance"),
      std::string("Wallpaper"),
      false,
      true,
      true,
      0,
      true,
      false,
      false,
      {},
      {
        {OptimizationValue{0}, std::string("Use Current Picture")},
        {OptimizationValue{1}, std::string("Solid Black Background")},
        {OptimizationValue{2}, std::string("Windows Spotlight")},
      }
    },
    {
      std::string("win.wallpaper.background.type"),
      std::string("Background Type (Advanced)"),
      std::string("Controls the type of desktop background (Picture, Solid Color, Slideshow, or Windows Spotlight) - Use Desktop Background Mode for easier control"),
      std::string("HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Wallpapers"),
      std::string("BackgroundType"),
      OptimizationValue{0},
      OptimizationValue{0},
      std::string("Appearance"),
      std::string("Wallpaper"),
      true,
      true,
      true,
      0,
      true,
      false,
      false,
      {},
      {
        {OptimizationValue{0}, std::string("Picture")},
        {OptimizationValue{1}, std::string("Solid Color")},
        {OptimizationValue{2}, std::string("Slideshow")},
      }
    },
    {
      std::string("win.wallpaper.spotlight.enabled"),
      std::string("Desktop Spotlight (Experimental)"),
      std::string("Controls whether Windows Spotlight is enabled for desktop backgrounds - WARNING: This registry key may not exist in Windows 11"),
      std::string("HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\DesktopSpotlight\\Settings"),
      std::string("EnabledState"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("Appearance"),
      std::string("Wallpaper"),
      true,
      true,
      false,
      2,
      true,
      true,
      false,
      {},
      {
        {OptimizationValue{0}, std::string("Disabled (for Picture, Solid Color, or Slideshow)")},
        {OptimizationValue{1}, std::string("Enabled (for Windows Spotlight)")},
      }
    },
    {
      std::string("win.wallpaper.spotlight.content"),
      std::string("Spotlight Content Delivery (Advanced)"),
      std::string("Controls Windows Spotlight content delivery for desktop backgrounds - Use Desktop Background Mode for easier control"),
      std::string("HKEY_CURRENT_USER\\Software\\Microsoft\\Windows\\CurrentVersion\\ContentDeliveryManager"),
      std::string("SubscribedContent-338389Enabled"),
      OptimizationValue{1},
      OptimizationValue{0},
      std::string("Appearance"),
      std::string("Wallpaper"),
      true,
      true,
      true,
      0,
      true,
      false,
      false,
      {},
      {
        {OptimizationValue{0}, std::string("Disabled (no Spotlight content)")},
        {OptimizationValue{1}, std::string("Enabled (allows Spotlight content)")},
      }
    },
    {
      std::string("win.wallpaper.style"),
      std::string("Wallpaper Display Style"),
      std::string("Controls how wallpaper images are displayed (Fill, Fit, Stretch, Tile, Center, Span)"),
      std::string("HKEY_CURRENT_USER\\Control Panel\\Desktop"),
      std::string("WallpaperStyle"),
      OptimizationValue{std::string("10")},
      OptimizationValue{std::string("10")},
      std::string("Appearance"),
      std::string("Wallpaper"),
      false,
      true,
      true,
      0,
      true,
      false,
      false,
      {},
      {
        {OptimizationValue{std::string("0")}, std::string("Center")},
        {OptimizationValue{std::string("2")}, std::string("Stretch")},
        {OptimizationValue{std::string("6")}, std::string("Fit")},
        {OptimizationValue{std::string("10")}, std::string("Fill (default)")},
        {OptimizationValue{std::string("22")}, std::string("Span")},
      }
    },
    {
      std::string("win.wallpaper.tile"),
      std::string("Wallpaper Tiling"),
      std::string("Controls whether wallpaper is tiled when using Center style"),
      std::string("HKEY_CURRENT_USER\\Control Panel\\Desktop"),
      std::string("TileWallpaper"),
      OptimizationValue{std::string("0")},
      OptimizationValue{std::string("0")},
      std::string("Appearance"),
      std::string("Wallpaper"),
      true,
      true,
      true,
      1,
      true,
      false,
      false,
      {},
      {
        {OptimizationValue{std::string("0")}, std::string("No Tiling (default)")},
        {OptimizationValue{std::string("1")}, std::string("Tile (repeat image)")},
      }
    },
    {
      std::string("win.wallpaper.path"),
      std::string("Wallpaper Image Path"),
      std::string("Specifies the full path to the wallpaper image file (only applies when Background Type is Picture) - READ ONLY for safety"),
      std::string("HKEY_CURRENT_USER\\Control Panel\\Desktop"),
      std::string("Wallpaper"),
      OptimizationValue{std::string("")},
      OptimizationValue{std::string("")},
      std::string("Appearance"),
      std::string("Wallpaper"),
      true,
      true,
      false,
      2,
      true,
      true,
      false,
      {},
      {
        {OptimizationValue{std::string("")}, std::string("No wallpaper (for solid color)")},
      }
    },
    {
      std::string("win.wallpaper.background.color"),
      std::string("Desktop Background Color (Advanced)"),
      std::string("Sets the RGB color for solid color backgrounds (format: 'R G B' e.g., '0 0 0' for black) - Use Desktop Background Mode for easier control"),
      std::string("HKEY_CURRENT_USER\\Control Panel\\Colors"),
      std::string("Background"),
      OptimizationValue{std::string("0 78 158")},
      OptimizationValue{std::string("0 0 0")},
      std::string("Appearance"),
      std::string("Wallpaper"),
      true,
      true,
      true,
      0,
      true,
      false,
      false,
      {},
      {
        {OptimizationValue{std::string("0 0 0")}, std::string("Black")},
        {OptimizationValue{std::string("255 255 255")}, std::string("White")},
        {OptimizationValue{std::string("0 78 158")}, std::string("Windows Blue (default)")},
        {OptimizationValue{std::string("64 64 64")}, std::string("Dark Gray")},
        {OptimizationValue{std::string("128 128 128")}, std::string("Medium Gray")},
      }
    },
  };
  return kRegistrySettings;
}

}  // namespace registry
}  // namespace optimizations